name: "Deploy to Hosted services"

on:
  workflow_dispatch:
    inputs:
      projOrg:
        required: true
        type: string
        default: centrifuge
      deploymentType:
        description: stage or primary
        required: false
        type: string
        default: stage

permissions:
  contents: read
  issues: write

jobs:
  subql_deploy_workflow:
    runs-on: ubuntu-latest
    env:
      SUBQL_INDEXER_VERSION: v3.1.0
      SUBQL_QUERY_VERSION: v2.6.0
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
      SUBQL_PROJ_ORG: ${{ inputs.projOrg }}
      SUBQL_DEPLOYMENT_TYPE: ${{ inputs.deploymentType }}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Yarn
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: SubQL CLI Version
        run: yarn subql --version
      - name: Publish SubQL version
        run: |
          npx subql publish -o -f . 
          ls -alh
          echo "CFG_IPFSCID=$(cat .project-cid)" >> $GITHUB_ENV
      - name: Deploy CFG Version
        run: |
          npx subql deployment:deploy \
          -d \
          --org="$SUBQL_PROJ_ORG" \
          --endpoint="wss://fullnode.parachain.centrifuge.io" \
          --projectName=centrifuge-dictionary  \
          --ipfsCID="$CFG_IPFSCID" \
          --type=$SUBQL_DEPLOYMENT_TYPE \
          --disableHistorical \
          --indexerVersion="$SUBQL_INDEXER_VERSION" \
          --queryVersion="$SUBQL_QUERY_VERSION"
