name: "Deploy to Hosted services"

on:
  workflow_dispatch:
    # inputs:
    #   directory:
    #     description: 'Dictionary directory name'
    #     required: true
    #     type: string
    #   projectYAML:
    #     description: 'project.yaml'
    #     required: false
    #     type: string
    #   projectName:
    #     description: 'Project name'
    #     required: true
    #     type: string
jobs:
  deploy:
    name: CLI Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: centrifuge
    environment:
      name: DEPLOYMENT
    env:
      SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: pwd
      - run: yarn
      - name: Codegen
        run: yarn codegen
      - name: Publish SubQL version
        run: |
          IPFSCID=$(npx subql publish -o -f .)
          echo "IPFSCID=$IPFSCID" >> $GITHUB_ENV
          echo "CID: $IPFSCID"
      - name: Deploy Version
        run: |
          npx subql deployment:deploy \
          -d \
          --org="centrifuge" \
          --projectName="centrifuge-dictionary" \
          --ipfsCID="$IPFSCID"
